add_library(queue_manager STATIC)

target_sources(queue_manager PRIVATE 
    "queue_manager.cpp"
)

target_include_directories(queue_manager PUBLIC 
    ${CMAKE_CURRENT_SOURCE_DIR}
)

target_link_libraries(queue_manager PUBLIC
    cubemx
)

target_compile_options(queue_manager PUBLIC
    -std=c23
    -Wall
    -Wextra
    -Wconversion
    -Wshadow
    -Wpedantic
    -Wnarrowing
    -Waddress
    -pedantic
    -Wdeprecated
    -Wsign-conversion
    -Wduplicated-cond
    -Wduplicated-branches
    -Wlogical-op
    -Wnull-dereference
    -Wdouble-promotion
    -Wimplicit-fallthrough
    -Wcast-align
    -Wformat=2
    -Wformat-security
    -Wmissing-prototypes
    -Wmissing-declarations
    -Wstrict-prototypes
    -Wold-style-definition
    -Wundef
    -Wvla
    -Wpointer-arith
    -Wstrict-aliasing=2
)